var i19={
	Username:'用户名',
	Password:'密码',
	Logon:'登陆',

	"STORE":'门店',
	"CASHIER":'收银',
	"PAYMENT":'结账',
	"STORE MANAGEMENT":'门店管理',
	"STAFF MANAGEMENT":'人员管理',
	"TABLE MANAGEMENT":'餐台管理',
	"STORE LAYOUT DESIGN":'门店布局设计',
	"DISH":'菜品',
	"DISH MANAGEMENT":'菜品管理',
	"MENU DESIGN":'菜单设计',
	"TENANT INFO":"公司信息",

	"30-Days Free Trial Application":"30天免费试用申请",
	"TENANT NAME":"公司名称",
	"STORE INFO":"门店信息",
	"ADMIN NAME":"管理员姓名",
	"ADMIN EMAIL/CP":"管理员邮箱或手机",
	"TENANT ADDRESS":"公司地址",
	CAPTCHA:"验证码",
	"Mandatory":"必填",
    "Mandatory,used for sign-in and receiving initial password":"必填，用于登陆和接收初始密码",
    "Please enter the CAPTCHA":"请输入验证码",

    "Province,AR,MU":"省 / 自治区 / 直辖市",
    "city":"市",
    "district":"区",
    "street address":"街区详细地址",

	new_item:'新菜品',
	item_name:'品名',
	item_code:'编号',
	item_desc:'详细描述',
	item_unit:'计量单位',
	item_category:'分类',
	item_image:'产品图片',
	price:'售价',

	unit_disk:'盘',
	unit_jin:'斤',
	unit_kg:'公斤',
	unit_bottle:'瓶',
	unit_cup:'杯',
	unit_ea:'个',

	type_foods:'菜品',
	type_goods:'货品',

	new_table:'新餐台',

	in_eat:'堂吃',
	take_out:'外带',
	number:'序号',
	quantity:'数量',
	total_amount:'总价',
	total_discount:'折扣',
	order_total_amount:'订单总价',
	order_total_discount:'订单总折扣',
	order_total_payment:'订单实付金额',
	pay_by_cash:'现金支付',
	pay_by_card:'信用卡支付',

	store:'门店',
	table_code:'桌号',
	dinner_person_count:'用餐人数',
	order_time:'下单时间',

	new_store:'新门店',
	store_name:'门店名',
	store_code:'门店号',
	store_desc:'门店介绍',
	store_address:'门店地址',
	telephone_1:'联系电话(主要)',
	telephone_2:'联系电话(备用)',
	business_hours:'营业时间',

	completed:'已完成',
	loading:'正在载入',
	loading_order:'正在读取订单',
	no_order_on_table:'没有查询到订单',
	saving:'正在保存',
	unknown_error:'未知错误',
	failure:'失败',

	save:'保存',
	submit:'提交',
	cancel:'取消'
};