ALTER TABLE DINING_TABLE DROP FOREIGN KEY FK_DINING_TABLE_ROOM_ID
ALTER TABLE ITEM DROP FOREIGN KEY FK_ITEM_ITEMTEMPLATE_ID
ALTER TABLE DELIVERY_LINE DROP FOREIGN KEY FK_DELIVERY_LINE_order_id
ALTER TABLE ORDER_LINE DROP FOREIGN KEY FK_ORDER_LINE_ORDER_ID
ALTER TABLE PAYMENT_LINE DROP FOREIGN KEY FK_PAYMENT_LINE_PAYMENT_ID
ALTER TABLE ITEM_TEMPLATE_PICTURE DROP FOREIGN KEY FK_ITEM_TEMPLATE_PICTURE_ITEM_TEMPLATE_ID
ALTER TABLE ITEM_TEMPLATE_CATEGORY DROP FOREIGN KEY FK_ITEM_TEMPLATE_CATEGORY_ITEM_TEMPLATE_ID
ALTER TABLE RULE_PARAMETER DROP FOREIGN KEY FK_RULE_PARAMETER_PROMOTION_ID
ALTER TABLE PROMOTION_CATEGORY DROP FOREIGN KEY FK_PROMOTION_CATEGORY_PROMOTION_ID
ALTER TABLE PROMOTION_ITEM DROP FOREIGN KEY FK_PROMOTION_ITEM_PROMOTION_ID
ALTER TABLE STORE_ADDRESS DROP FOREIGN KEY FK_STORE_ADDRESS_STORE_ID
DROP TABLE DELIVERY
DROP TABLE ORDERS
DROP TABLE PAYMENT
DROP INDEX IDX_CATEGORY_T_CODE ON CATEGORY
DROP INDEX INDEX_CATEGORY_CODE ON CATEGORY
DROP TABLE CATEGORY
DROP INDEX IDX_DT_BAR_CODE ON DINING_TABLE
DROP INDEX IDX_DT_NUMBE ON DINING_TABLE
DROP TABLE DINING_TABLE
DROP INDEX INDEX_ITEM_CODE ON ITEM
DROP TABLE ITEM
DROP INDEX IDX_ITEM_TPL_T_CODE ON ITEM_TEMPLATE
DROP INDEX IDX_ITEM_TPL_T_NAME ON ITEM_TEMPLATE
DROP INDEX INDEX_ITEM_TEMPLATE_CODE ON ITEM_TEMPLATE
DROP TABLE ITEM_TEMPLATE
DROP INDEX INDEX_PROMOTION_CODE ON PROMOTION
DROP TABLE PROMOTION
DROP INDEX IDX_ROOM_STR_CODE ON ROOM
DROP INDEX IDX_ROOM_STR_NAME ON ROOM
DROP INDEX INDEX_ROOM_CODE ON ROOM
DROP TABLE ROOM
DROP INDEX IDX_STORE_T_CODE ON STORE
DROP INDEX IDX_STORE_T_NAME ON STORE
DROP INDEX INDEX_STORE_CODE ON STORE
DROP TABLE STORE
DROP INDEX INDEX_USERS_EMAIL ON USERS
DROP INDEX INDEX_USERS_TELEPHONE ON USERS
DROP TABLE USERS
DROP TABLE DELIVERY_LINE
DROP TABLE ORDER_LINE
DROP TABLE PAYMENT_LINE
DROP TABLE ITEM_TEMPLATE_PICTURE
DROP TABLE ITEM_TEMPLATE_CATEGORY
DROP TABLE RULE_PARAMETER
DROP TABLE PROMOTION_CATEGORY
DROP TABLE PROMOTION_ITEM
DROP TABLE STORE_ADDRESS
